language: objective-c
osx_image: xcode9.3
os: osx

install:
  - carthage bootstrap --platform ios

script:
  - xcodebuild test -sdk iphonesimulator -workspace ABChoiceView.xcworkspace -scheme ABChoiceExampleTests -destination 'platform=iOS Simutor,name=iPhone 8'
