language: objective-c
osx_image: xcode9.3
os: osx

cache:
  directories:
    - Carthage

before_install:
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - xcodebuild test -sdk iphonesimulator -workspace ABChoiceView.xcworkspace -scheme ABChoiceExampleTests -destination 'platform=iOS Simulator,name=iPhone 8'
