language: objective-c
osx_image: xcode9.3
os: osx

before_install:
  - brew update || brew update
  - brew install carthage || brew outdated carthage || brew upgrade carthage
install:
  - carthage bootstrap

xcode_project: ABChoiceExample/ABChoiceExample.xcodeproj
xcode_scheme: ABChoiceExampleTests
